-- Web push (roadmap 10.1): one row per browser the user allowed notifications in.
create table push_subscriptions (
    id               bigint generated by default as identity,
    user_id          bigint        not null,
    endpoint         varchar(1000) not null,
    p256dh           varchar(100)  not null,
    auth             varchar(50)   not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint push_subscriptions_pkey primary key (id),
    constraint uk_push_subscriptions_endpoint unique (endpoint),
    constraint fk_push_subscriptions_user foreign key (user_id) references users (id) on delete cascade
);
create index idx_push_subscriptions_user_id on push_subscriptions (user_id);
