-- DevHabit schema as Hibernate generated it from the entities on 2026-10-07 (roadmap D.1).
-- Constraint and foreign-key names are Hibernate's own, so databases created before Flyway
-- (baselined at version 1) and databases created by this script are identical.
-- Applied migrations are never edited: change the schema with a new V{n}__description.sql.

create table users (
    id               bigint generated by default as identity,
    email            varchar(320) not null,
    password_hash    varchar(100),
    name             varchar(100) not null,
    auth_provider    varchar(20)  not null,
    provider_id      varchar(255),
    timezone         varchar(64)  not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_auth_provider_check check (auth_provider in ('LOCAL', 'GOOGLE'))
);

create table refresh_tokens (
    id               bigint generated by default as identity,
    user_id          bigint      not null,
    token_hash       varchar(64) not null,
    expires_at       timestamp(6) with time zone not null,
    revoked          boolean     not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint refresh_tokens_pkey primary key (id),
    constraint refresh_tokens_token_hash_key unique (token_hash),
    constraint fk1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users (id)
);
create index idx_refresh_tokens_user_id on refresh_tokens (user_id);

create table goals (
    id               bigint generated by default as identity,
    user_id          bigint       not null,
    title            varchar(120) not null,
    description      varchar(2000),
    target_date      date,
    status           varchar(20)  not null,
    achieved_at      timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint goals_pkey primary key (id),
    constraint goals_status_check check (status in ('ACTIVE', 'ACHIEVED', 'ABANDONED')),
    constraint fkb1mp6ulyqkpcw6bc1a2mr7v1g foreign key (user_id) references users (id)
);
create index idx_goals_user_id on goals (user_id);

create table habits (
    id               bigint generated by default as identity,
    user_id          bigint       not null,
    name             varchar(120) not null,
    category         varchar(50),
    frequency_type   varchar(20)  not null,
    frequency_config jsonb,
    target_count     integer      not null,
    reminder_time    time(0) without time zone,
    archived         boolean      not null,
    goal_id          bigint,
    goal_target_days integer,
    goal_linked_on   date,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint habits_pkey primary key (id),
    constraint habits_frequency_type_check check (frequency_type in ('DAILY', 'SPECIFIC_DAYS', 'X_TIMES_PER_WEEK')),
    constraint fkg3n2qqwmsyv3517xdcosouk9i foreign key (user_id) references users (id),
    constraint fkjeuc8h34b3hire0wlw4ou9w3m foreign key (goal_id) references goals (id)
);
create index idx_habits_user_id on habits (user_id);
create index idx_habits_goal_id on habits (goal_id);

create table habit_logs (
    id               bigint generated by default as identity,
    habit_id         bigint  not null,
    log_date         date    not null,
    completed_count  integer not null,
    note             varchar(500),
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint habit_logs_pkey primary key (id),
    constraint uk_habit_logs_habit_date unique (habit_id, log_date),
    constraint fksoqj2dqbm162ouaydnbwb21uj foreign key (habit_id) references habits (id)
);

create table notifications (
    id               bigint generated by default as identity,
    user_id          bigint       not null,
    type             varchar(30)  not null,
    title            varchar(150) not null,
    body             varchar(500) not null,
    habit_id         bigint,
    for_date         date,
    read_at          timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint notifications_pkey primary key (id),
    constraint uk_notifications_habit_date_type unique (habit_id, for_date, type),
    constraint notifications_type_check check (type in ('HABIT_REMINDER')),
    constraint fk9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users (id),
    constraint fkechmhnlewtjn0m7jjmy8jilqb foreign key (habit_id) references habits (id)
);
create index idx_notifications_user_id on notifications (user_id);

create table stored_files (
    id               bigint generated by default as identity,
    user_id          bigint       not null,
    storage_key      varchar(36)  not null,
    original_name    varchar(255) not null,
    content_type     varchar(100) not null,
    size_bytes       bigint       not null,
    sha256           varchar(64)  not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint stored_files_pkey primary key (id),
    constraint stored_files_storage_key_key unique (storage_key),
    constraint fkc0pxhjsng9h58ifnju7u0hol3 foreign key (user_id) references users (id)
);
create index idx_stored_files_user_id on stored_files (user_id);

create table resources (
    id               bigint generated by default as identity,
    user_id          bigint       not null,
    goal_id          bigint,
    type             varchar(10)  not null,
    title            varchar(200) not null,
    body             text,
    url              varchar(2048),
    file_id          bigint,
    pinned           boolean      not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint resources_pkey primary key (id),
    constraint resources_file_id_key unique (file_id),
    constraint resources_type_check check (type in ('NOTE', 'LINK', 'FILE')),
    constraint fkcoba1blh4w96p6n34i4xfoiyp foreign key (user_id) references users (id),
    constraint fkgqt74sm1lh3p0v24ge4jqpdu4 foreign key (goal_id) references goals (id),
    constraint fked1l07cx4d2f1megskbpha9lq foreign key (file_id) references stored_files (id)
);
create index idx_resources_user_id on resources (user_id);
create index idx_resources_goal_id on resources (goal_id);
