-- Forgot password (roadmap 2.4a): one-time reset links. Only the SHA-256 of a token is stored.

create table password_reset_tokens (
    id               bigint generated by default as identity,
    user_id          bigint      not null,
    token_hash       varchar(64) not null,
    expires_at       timestamp(6) with time zone not null,
    used_at          timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(320),
    last_modified_at timestamp(6) with time zone,
    last_modified_by varchar(320),
    constraint password_reset_tokens_pkey primary key (id),
    constraint uk_password_reset_tokens_token_hash unique (token_hash),
    constraint fk_password_reset_tokens_user foreign key (user_id) references users (id)
);
-- the per-user limits count a user's recent requests
create index idx_password_reset_tokens_user_created on password_reset_tokens (user_id, created_at);
